### PR TITLE
Adds OpenLab Portfolio

### LINKED ISSUE #200: Add to Portfolio
The OpenLab team would like to port its 'Add to Portfolio' functionality to the CBOX-OL package.

I'll assign this ticket to @mamaduka once he's accepted my invite to the team :)

### PR DESCRIPTION
**Pull request by Mamaduka**
Adds portfolio features as a required plugin.

This PR fixes #200 and #201.

### CODE REVIEW

**Comment by boonebgorges** [comment]
Thanks @Mamaduka !

@r-a-y Do we have a procedure for adding a new Required plugin? In the same way that we get the "x plugins require updates" message when you have a pending update, we probably ought to have a "x plugins need to be installed" message or something similar when CBOX sees that one of the required plugins is missing. But in my testing this does not happen: I see it on the list of Required plugins and can install it from there, but I'm not prompted to do so. Could you have a look and let me know your thoughts?

**Comment by r-a-y** [comment]
@boonebgorges I don't think we've ever added new Required plugins mid-cycle, so what you write sounds correct and I'll need to look into it.

It looks like OpenLab Portfolio is slated for the next major release (1.2.0) and not the upcoming maintenance release (1.1.3). Can you confirm?

**Comment by boonebgorges** [comment]
Thanks @r-a-y !

> It looks like OpenLab Portfolio is slated for the next major release (1.2.0) and not the upcoming maintenance release (1.1.3). Can you confirm?

Because the OpenLab package is ready to ship a couple of significant features (or at least it will be in a month from now) I was thinking we'd just call the next release 1.2.0. Do you have an objection to that? Instead of separating it out into a separate maintenance release.

**Comment by r-a-y** [comment]
No objection. Just wasn't sure about the version numbering! I'll adjust some of my other commits that were referencing 1.1.3.

**Comment by boonebgorges** [comment]
Thank you! It's an art and not a science ;)

**Comment by r-a-y** [comment]
A notice is now shown if a required plugin is missing. See #217.

@Mamaduka - Can you change the merge branch from `master` to `1.2.x`? Once you've done that, we can merge. Thanks!

**Comment by Mamaduka** [comment]
Thanks, @r-a-y.

I've updated the merge branch but it messes up the history. Should I close this one PR and create a new one with proper branches?

**Comment by r-a-y** [comment]
@Mamaduka - Yes, let's create a new PR. Thanks!

**Pull request closed without merging**
